name: simple-haskell
version: 0.1.0.0
github: "cheukwing/simple-haskell"
license: MIT
author: "Michael Tsang"
maintainer: "me@cheukwing.dev"
copyright: "2020 Michael Tsang"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/cheukwing/simple-haskell#readme>

dependencies:
  - base >= 4.7 && < 5
  - array
  - mtl
  - haskeline
  - tasty
  - tasty-hunit

library:
  source-dirs: src

executables:
  simple-haskell-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - simple-haskell

tests:
  simple-haskell-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - simple-haskell
